### ISSUE TITLE
getting issue on frontend after installation  "ScopeConfigInterface"

### ISSUE THREAD

**Issue by ved1585** [opengento/magento2-country-store-switcher#1]
( ! ) Parse error: syntax error, unexpected 'ScopeConfigInterface' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/html/app/code/Opengento/CountryStoreSwitcher/ViewModel/Localized.php on line 23

**Comment by thomas-kl1** [comment]
Hi, is the codebase running on php74 or above?
